# pyproject.toml

[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dlo_seg"
version = "0.1.0"
description = "A toolkit for segmentation and analysis of deformable linear objects in robotics"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"

authors = [
  { name = "Your Name", email = "you@domain.com" }
]
maintainers = [
  { name = "Your Name", email = "you@domain.com" }
]
keywords = ["robotics", "DLO", "segmentation", "computer-vision"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

# All tools—dev, geometry, vision—now live here
dependencies = [
  "numpy>=1.23,<2.0",
  "scipy>=1.9,<2.0",
  "scikit-image>=0.19,<0.21",
  "opencv-contrib-python>=4.5,<4.8",
  "timm>=0.6,<0.7",
  "albumentations>=1.3,<2.0",
  "scikit-learn>=1.1,<1.3",
  "networkx>=3.0,<4.0",
  "matplotlib>=3.5,<4.0",
  "tqdm>=4.66.1,<5.0",
  "hydra-core>=1.3.2,<1.4.0",
  "iopath>=0.1.10,<0.2.0",
  "pillow>=9.4.0,<10.0",
  "pyyaml>=6.0,<7.0",
  "ruamel.yaml>=0.17,<1.0",
  "open3d>=0.15,<0.16",
  "trimesh>=3.19,<4.0",
  "transformers>=4.30,<5.0",
  "einops>=0.6,<1.0",
  "gdown>=4.6,<5.0",
  "supervision>=0.22.0,<0.23.0",
  "pycocotools>=2.0,<3.0",
  "imageio>=2.25,<3.0",
  "addict>=2.4,<3.0",
  "yapf>=0.32,<0.35",
  "typeguard>=2.13,<3.0",

  # Previously “dev” extras:
  "jupyterlab>=3.5,<4.0",
  "pytest>=7.0,<8.0",
  "flake8>=4.0,<5.0",
  "black>=23.1,<24.0"
]

# If you have CLI entry points, you can still declare them here:
# [project.scripts]
# dlo-segment = "dlo_seg.cli:main"

[project.urls]
"Homepage" = "https://github.com/your-org/dlo_seg"
"Issue Tracker" = "https://github.com/your-org/dlo_seg/issues"
"Documentation"   = "https://your-org.github.io/dlo_seg/"

# setuptools-specific in-TOML options
[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["dlo_seg*"]
