[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dlo_seg"
version = "0.1.0"
dependencies = [
    "torch==2.5.1",
    "torchvision>=0.20.1",
    "torchaudio==2.5.1",
    "numpy>=1.24.4",
    "tqdm>=4.66.1",
    "hydra-core>=1.3.2",
    "iopath>=0.1.10",
    "pillow>=9.4.0",
    "pyyaml",
    "typeguard",
    "opencv-python",
    "supervision",
    "pycocotools",

]
dynamic = ["description", "readme", "license", "authors", "requires-python"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
dlo_seg = ["requirements.txt"]